import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LoginButton from "@/components/LoginButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-black text-white antialiased`}
      >
        <header className="fixed inset-x-0 top-0 z-50 border-b border-white/10 bg-black/95 backdrop-blur">
          <nav className="mx-auto flex max-w-5xl flex-wrap items-center justify-between gap-4 px-6 py-4 text-sm font-medium uppercase tracking-wide">
            <Link
              href="/"
              className="text-lg font-semibold text-white transition-colors hover:text-yellow-400"
            >
              Delta Force Hub
            </Link>
            <div className="flex flex-wrap items-center gap-4 text-white">
              {[
                { href: "/", label: "홈" },
                { href: "/gunsmith", label: "총기모딩" },
                { href: "/map", label: "맵 전략" },
                { href: "/news", label: "뉴스" },
                { href: "/board", label: "전술 게시판" },
              ].map((item) => (
                <Link
                  key={item.href}
                  href={item.href}
                  className="transition-colors hover:text-yellow-400 focus-visible:rounded focus-visible:outline focus-visible:outline-2 focus-visible:outline-yellow-400"
                >
                  {item.label}
                </Link>
              ))}
              <LoginButton />
            </div>
          </nav>
        </header>
        <main className="pt-24">{children}</main>
      </body>
    </html>
  );
}
